name: Minecraft Shutdown with Countdown

on:
  workflow_dispatch: # manual start button
  schedule:
    - cron: "0 2 * * *" # auto shutdown at 02:00 (adjust!)

jobs:
  shutdown:
    runs-on: ubuntu-latest

    steps:
      - name: Install mcrcon
        run: |
          sudo apt update
          sudo apt install -y mcrcon

      - name: Countdown start
        run: |
          mcrcon -H ${{ secrets.MC_HOST }} \
                 -P ${{ secrets.RCON_PORT }} \
                 -p ${{ secrets.RCON_PASS }} \
                 "say §c⚠ Server shutting down in 60 seconds!"

          sleep 30

          mcrcon -H ${{ secrets.MC_HOST }} -P ${{ secrets.RCON_PORT }} -p ${{ secrets.RCON_PASS }} \
          "say §e⏳ 30 seconds remaining!"

          sleep 20

          mcrcon -H ${{ secrets.MC_HOST }} -P ${{ secrets.RCON_PORT }} -p ${{ secrets.RCON_PASS }} \
          "say §c⏳ 10 seconds remaining!"

          sleep 10

      - name: Stop server
        run: |
          mcrcon -H ${{ secrets.MC_HOST }} \
                 -P ${{ secrets.RCON_PORT }} \
                 -p ${{ secrets.RCON_PASS }} \
                 "stop"
